services:
  pgsql:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - postgres_data_safelab:/var/lib/postgresql/data
    ports:
      - ${PORT_DB}:5432

  python:
    build:
      context: .
      dockerfile: ./.docker/python.Dockerfile
    depends_on:
      - pgsql
    ports:
      - 5000:5000
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data_safelab:
