"""tirando columa tipo

Revision ID: 4d56af346569
Revises: 00f6689fe0e8
Create Date: 2024-09-24 01:25:13.404330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d56af346569'
down_revision = '00f6689fe0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
